<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Challenge extends Unicore
{
    function init()
    {
        $this->uni('codingGrounds')
            ->includeJs(path . '/asset/codemirror-5.53.2/lib/codemirror.js', ['base'=>base])
            ->callback($this, 'codeMirrorSetup')
            ->hook('main','challenge')
            ->output();
    }

    function codeMirrorSetup($uni)
    {
        $uni->includeJs(path . '/asset/codemirror-5.53.2/mode/javascript/javascript.js', ['base'=>base]);
        $uni->addStylesheet(base . '/asset/codemirror-5.53.2/lib/codemirror.css');
        return $uni;
    }

}
