<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Apps\Db;
use Neoan3\Core\Serve;

class CodingGrounds extends Serve
{
    private $credentials;
    function __construct()
    {
        parent::__construct();
        $this->header = file_get_contents(__DIR__. '/header.html');
        try{
            $this->credentials = getCredentials();
            // user, host, password, assumes_uuid, name
            Db::setEnvironment($this->credentials['codingGrounds_db']);
        } catch (\Exception $exception){
            die('SETUP failed');
        }

    }
    function constants()
    {
        return [
            'stylesheet' => [
                '' . base . 'frame/codingGrounds/style.css',
            ]
        ];
    }
}
