<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class ToDo extends Unicore
{
    function init()
    {
        $toDoList = [
            ['name' => 'login/auth', 'done' => false],
            ['name' => 'models', 'done' => false],
            ['name' => 'environment', 'done' => false],
        ];
        $this->uni('codingGrounds')
            ->hook('main','toDo', ['list'=>$toDoList])
            ->output();
    }

}
